### ISSUE TITLE
Does not have mobile functionality

### ISSUE THREAD

**Issue by BriannaBromell** [arconnectio/ArConnect#47]
Can't use on mobile at all, extensions can't interact with mobile browsers.

**Comment by cromatikap** [comment]
Hi, I think this issue is solved 👍 

You can use [MathWallet](https://mathwallet.org) on iOS/Android, it is [compatible with the ArConnect API](https://doc.mathwallet.org/en/ar/).
It is also easily possible [to submit a dApp](https://m.maiziqianbao.net/submit/dapp) on the [dApp Store](https://mathdapp.store/).

That's pretty awesome.
